### ISSUE TITLE
Current code not working

### ISSUE THREAD

**Issue by Darth-Ness** [redstone-scratch/Snazzle#20]
After running `git pull` on my local copy (updating it with the code on GitHub) it doesn't run anymore. I'm looking into want is wrong and hopefully will start a PR soon.

Just in case your curious, this is the error.

> {'user_theme': 'choco', 'user_name': 'CoolScratcher123', 'pinned_subforums': []}
127.0.0.1 - - [27/Jul/2023 08:16:18] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sky/Documents/Code/Snazzle/main.py", line 136, in index
    return stream_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 197, in stream_template
    return _stream(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 165, in _stream
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 997, in update_template_context
    context.update(func())
                   ^^^^^^^
  File "/home/sky/Documents/Code/Snazzle/main.py", line 121, in context
    theme=user_data['theme'],

**Comment by EngineerRunner** [comment]
the bottom issue can be fixed by changing it to `theme=user_data['theme]`, try that first

**Comment by Darth-Ness** [comment]
Lol, I was just typing that was the issue. Yeah. That did fix it. I'm now going to try and fix a issue where the themes won't change. I think this is because of the big forum changes.

**Comment by EngineerRunner** [comment]
fixed issue in latest commit

**Comment by Darth-Ness** [comment]
That commit doesn't fix it. It seems like the user_theme thing is never being changed in the first place.

**Comment by EngineerRunner** [comment]
oh it fixed the issue with the errors, ima make a new issue for the actual themes

**Comment by Darth-Ness** [comment]
Oh okay. That did fix that issue.

**Comment by redstone-scratch** [comment]
> That commit doesn't fix it. It seems like the user_theme thing is never being changed in the first place.

It gets changed when you GET `/settings?theme=<theme>`
